image: openjdk:11

before_script:
   - apt-get update
   - apt-get -y install ant

stages:
   - build
   - test

ci_build:
   stage: build
   script:
      - javac -cp .classpath src/LaunchServer.java
      - javac -cp .classpath src/LaunchClientGUI.java
   
ci_test:
   stage: test
   script:
      - cd src/test
      - ant clean build DatabaseTest
